#include<iostream>
using namespace std;
int main()
{
  int a, b;
  cin>>a>>b;
  try
  {
    if (b!=0)
    cout<<"division:"<<a/b<<endl;
    else if (b==0)
    throw b;
  }
  catch(int b)
  {
    cout<<"exception caught"<< endl;
  }
}
